### ISSUE TITLE
768MB app memory

### ISSUE THREAD

**Issue by amdelamar** [amdelamar/vertx-cloudfoundry#2]
Forcing Java apps to use 768MB or higher is cumbersome. 

So here is an unofficial workaround to limit the memory to 512MB per instance:

```yaml
applications:
- path: ./build/libs/vertx-cloudfoundry-0.1.0-all.jar
  memory: 512M
  instances: 1
  name: my-vertx-app
  buildpack: https://github.com/cloudfoundry/java-buildpack.git
  env:
    JBP_CONFIG_OPEN_JDK_JRE: '{ memory_calculator : { memory_sizes : { heap : 512m } } }'
    JAVA_OPTS: '-XX:MaxMetaspaceSize=150M -Xss228k'
```
